# Generated by Django 4.2.7 on 2023-11-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AddField(
            model_name='articles',
            name='kategor',
            field=models.CharField(default='', max_length=50, verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
